- composer.json
**Copy of https://github.com/optimizely/php-sdk/issues/20 (moved to `devel` branch)**
Composer itself (and related packages such as webmozart/json) requires json-schema ^1.6 or ^2.0, making this package impossible to use within a project.
I've added the required versions, and tests still run fine. However I'm assuming this was set to 4.0.0 for a reason?
> Lowered version for json-schema

- src/Optimizely/Bucketer.php
- src/Optimizely/Entity/Experiment.php
- src/Optimizely/Event/Builder/EventBuilder.php
- src/Optimizely/Optimizely.php
- tests/BucketerTest.php
- tests/EventTests/EventBuilderTest.php
- tests/OptimizelyTest.php
> Refactor order of bucketing logic

- src/Optimizely/ProjectConfig.php
- tests/OptimizelyTest.php
Added more unit tests for forced bucketing. Added check for invalid user IDs. Also replaced empty with \!isset and is_null to properly reflect the desired behavior of checking for null and empty string values.
> Forced Bucketing Improvements

- src/Optimizely/Optimizely.php
- tests/OptimizelyTest.php
Make sure that the `isFeatureEnabled` API always returns a boolean.
> Fix isFeatureEnabled to always return a boolean value.

- src/Optimizely/Optimizely.php
- tests/OptimizelyTest.php
- tests/TestData.php
📝  Impression event dispatching logic was separated into another method 'sendImpressionEvent'
📝  An event was added to test data to cover an uncovered scenario via unit testing.
> sendImpressionEvent and TestData update

- CHANGELOG.md
- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
I'll cherry-pick this into 1.5.0 once this has been landed.
> Updated the Changelog for 1.5.0 release.

- src/Optimizely/ProjectConfig.php
In PHP, if a numeric string is a valid integer, it is auto converted into an integer before being stored as a key in an associative array. So you can not have integer string as a key. 
array_merge has a weird behavior, it re-indexes all numerical keys, starting from zero. 
See this here: https://repl.it/@oakbani/arraymerge-or
Since we allow experiment and variation keys to be saved only as numbers, this could break SDK functionality. We can use + operator instead as we will have unique keys in our data file.
> Use + operator instead of array_merge

- src/Optimizely/Logger/DefaultLogger.php
- src/Optimizely/Optimizely.php
- tests/LoggerTests/DefaultLoggerTest.php
- tests/OptimizelyTest.php
Log to STDOUT by default.
Output stream is configurable.
> Modify Default Logger

- src/Optimizely/Event/Builder/EventBuilder.php
- src/Optimizely/Optimizely.php
- src/Optimizely/Utils/EventTagUtils.php
- tests/EventTests/EventBuilderTest.php
- tests/NotificationTests/NotificationCenterTest.php
- tests/OptimizelyTest.php
- tests/UtilsTests/EventTagUtilsTest.php
https://github.com/optimizely/php-sdk/pull/91 revealed that though we do log in EventTagUtils-getNumericValue(), we do not pass it a logger from event builder, thus nothing is logged in actual activate/track use case.
> Add logger to getNumericValue in EventBuilder

- src/Optimizely/Optimizely.php
- tests/OptimizelyTest.php
📝 Convert http_build_query to json_encode
**Current:** 
> URL https://logx.optimizely.com/v1/events with params account_id=7947771809&project_id=8168934166&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bdecisions%5D%5B0%5D%5Bcampaign_id%5D=10165816054&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bdecisions%5D%5B0%5D%5Bexperiment_id%5D=10160995869&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bdecisions%5D%5B0%5D%5Bvariation_id%5D=10177144923&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bevents%5D%5B0%5D%5Bentity_id%5D=8237670087&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bevents%5D%5B0%5D%5Btimestamp%5D=1519383011000&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bevents%5D%5B0%5D%5Buuid%5D=4e466784-8b2c-4d33-8ff2-9e3e198e2e0e&visitors%5B0%5D%5Bsnapshots%5D%5B0%5D%5Bevents%5D%5B0%5D%5Bkey%5D=order&visitors%5B0%5D%5Bsnapshots%5 …
> Make event payload log readable

- src/Optimizely/Notification/NotificationCenter.php
- tests/NotificationTests/NotificationCenterTest.php
Renames 'clearNotifications' to 'clearNotificationListeners' and 'cleanAllNotifications' to 'clearAllNotificationListeners'.
Added deprecated methods along '@deprecated' meta tag.
> Renames notification-center methods

- composer.json
PSR-4 autoloaders with no prefix can hurt performance, especially in large projects with many dependencies. When resolving class names to files, if Composer cannot use a prefix to limit the search paths, it has to search every autoloader with a blank prefix.
This change adds a prefix to the autoloader, to avoid this problem.
Running `composer diagnose` previously reported this:
```
~/src/php-sdk % composer diagnose
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
```
With this change, `composer diagnose` is happy.
I couldn't add tests for this, because it's not a code change. But, I did run the test suite to verify that it everything still passes as expected.
> Add prefix to PSR-4 autoloader

- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
- tests/ProjectConfigTest.php
- tests/TestData.php
Note: Sending one more PR on php-testapp, getting failed on FS track mng/add-test-for-multiple-events
> fix(track): Send decisions for all experiments using an event when using track

- src/Optimizely/Optimizely.php
- src/Optimizely/ProjectConfig.php
- tests/ProjectConfigTest.php
Forced variation key passed as an empty String will be invalid argument.
- Updated inputs validation for setForcedVariation.
- Updated unit tests for empty string variation key.
> fix(setForcedVariation): Treats empty variation key as invalid and does not reset forced variation.

- src/Optimizely/Bucketer.php
on x86, when 32 bit hash code is generated, it overflows and fall into float type which causes the number into negative and beyond out of range. 
The "why", or other context.
- "THING-1234" or "Fixes #123"
> fix(generateBucketValue): Avoid negative bucket number for PHP x86

- src/Optimizely/Bucketer.php
docs for change in https://github.com/optimizely/php-sdk/pull/137
- OASIS-3730
> docs (generateBucketValue): Reasoning for incrementing bucket num by 10,000 for x86

- src/Optimizely/Optimizely.php
- src/Optimizely/ProjectConfig.php
- tests/OptimizelyTest.php
- Allow empty user ID in all APIs.
- Added/Updated unit tests.
> refact(API): Validates empty user ID as valid.

- src/Optimizely/Utils/Validator.php
- tests/UtilsTests/ValidatorTest.php
Summary
-------
Don't target NAN, INF or -INF doubles
Don't target Values > 2^53.
Both in EventBuilder payload and Audience Evaluation
- OASIS-3656
- https://github.com/optimizely/python-sdk/pull/146#discussion_r237850806
> feat(attribute_value): Don't target NAN, INF, -INF and > 2^53

- src/Optimizely/ProjectConfig.php
- src/Optimizely/Utils/Validator.php
- tests/ProjectConfigTest.php
- tests/UtilsTests/ValidatorTest.php
In Audience Evaluation, evaluate unknown audience to null and continue evaluation for other audiences. 
Though we trust the datafile generation part won't generate such scenario, we still check to sync up with compat suite test here:
https://github.com/optimizely/fullstack-sdk-compatibility-suite/pull/196
Ran compatibility suite including audience combination tests. 
- OASIS-3921
> fix(audience evaluation): evaluate unknown audience id to null and continue

- src/Optimizely/Event/Builder/EventBuilder.php
- src/Optimizely/Event/Builder/Params.php
- src/Optimizely/Optimizely.php
- tests/EventTests/EventBuilderTest.php
- tests/OptimizelyTest.php
- Impression/Conversion events now have a 'enrich_decisions' boolean property set to true.
- conversion events now do not have the decision property in visitor snapshots. 
- Conversion event is now sent solely if the event key corresponds to a valid event in the data file. Number of experiments attached to the event, or status of experiment, or the bucketing does not make a difference. 
- Unit Tests updated
- Additional Unit Test added for paused experiment.
- Tested Compat Suite Tests for EET locally and via Travis on custom triggered build. 
- OASIS-4030
> feat(track): Introducing easier event tracking

- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/Enums/AudienceEvaluationLogs.php
- src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
- src/Optimizely/Utils/Validator.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- tests/UtilsTests/CustomAttributeConditionEvaluatorLoggingTest.php
- tests/UtilsTests/CustomAttributeConditionEvaluatorTest.php
- tests/UtilsTests/ValidatorLoggingTest.php
- tests/UtilsTests/ValidatorTest.php
Summary
-------
This adds logging to audience evaluation. 
For now, logging is limited to issues with user passed value and not the condition value (datafile). 
- Updated Unit Tests in OptimizelyTest and DecisionServiceTest to assert only relevant logs. Position based logging had to be removed since isUserInExperiment is a static method and can not be mocked. 
- Added new tests for isUserInExperiment and CustomAttributeConditionEvaluator
- OASIS-3854
> feat(Audience Evaluation): Audience Logging

- CHANGELOG.md
- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
- Updating version number and change log for 3.0.0 release.
> Preparing for 3.0.0 release

- src/Optimizely/Optimizely.php
- tests/OptimizelyTest.php
- Feature variable APIs now return default variable value when featureEnabled property is false.
- Added unit tests.
> feat(api): Feature variable APIs return default variable value when featureEnabled property is false.

- src/Optimizely/Optimizely.php
- tests/OptimizelyTest.php
- Resolves variable value type cast issue.
- Updated unite tests.
> Fix(FeatureVariable): Resolves variable value type cast issue

- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/DecisionService/FeatureDecision.php
- src/Optimizely/Enums/DecisionNotificationTypes.php
- src/Optimizely/Optimizely.php
- src/Optimizely/ProjectConfig.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- tests/ProjectConfigTest.php
- tests/TestData.php
- Incorporated new decision notification listener changes.
- Updated test data to fix experiment to feature relationship.
- Added unit tests for type `feature-test` and project config method.
- Updated unit tests.
> feat(decision-listener): Incorporated new decision notification listener changes.

- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/Optimizely.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- Moved ProjectConfig from DecisionService constructor to individual methods
- Updated unit tests.
> refact(decisionService): Move ProjectConfig from DecisionService constructor to individual methods

- src/Optimizely/Optimizely.php
- src/Optimizely/ProjectConfigManager/HTTPProjectConfigManager.php
Current setup ends up in project config manager having its own notification center and Optimizely class having its own center. This change allows us to declare a notification center and share it between the two in order to accurately set up and use listeners.
> Allow notification center to be passed in to Optimizely

- README.md
This updates readme for factory method introduced in https://github.com/optimizely/php-sdk/pull/189
All checks continue to pass. 
- OASIS-6246
> docs: Add steps for sdk key init

- src/Optimizely/Config/DatafileProjectConfig.php
- src/Optimizely/Entity/FeatureVariable.php
- src/Optimizely/Enums/DecisionNotificationTypes.php
- src/Optimizely/Optimizely.php
- src/Optimizely/Utils/VariableTypeUtils.php
- tests/ConfigTests/DatafileProjectConfigTest.php
- tests/OptimizelyConfigTests/OptimizelyConfigServiceTest.php
- tests/OptimizelyTest.php
- tests/TestData.php
Implemented getFeatureVariableJson and getAllFeatureVariables
1-[ Tested with FSC](https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/164662165)
2- Added Unit tests
> feat: Added getFeatureVariableJson and getAllFeatureVariables

- composer.json
Icecave/Parity library is being used in unit tests. This PR moves it to dev dependencies so that this doesn't get installed when SDK is used as a library in another project. 
All checks pass.
> build: move icecave/parity to dev dependencies

- src/Optimizely/Utils/Validator.php
- tests/UtilsTests/ValidatorLoggingTest.php
Modifying log level for single audience evaluation from INFO to DEBUG to reduce noise in logs. Now, only combined audience evaluation is logged at INFO level.
All checks pass
- OASIS-6524
> fix(log-level) change single audience result to debug

- src/Optimizely/Bucketer.php
- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/Enums/AudienceEvaluationLogs.php
- src/Optimizely/Enums/CommonAudienceEvaluationLogs.php
- src/Optimizely/Enums/ExperimentAudienceEvaluationLogs.php
- src/Optimizely/Enums/RolloutAudienceEvaluationLogs.php
- src/Optimizely/Optimizely.php
- src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
- src/Optimizely/Utils/Validator.php
- tests/BucketerTest.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- tests/UtilsTests/ValidatorLoggingTest.php
- tests/UtilsTests/ValidatorTest.php
- This PR modifies log messages to be explicit when it's evaluating an experiment and when it's doing so for a Rollout. 
- Added additional unit test to assert audience logs for rollouts. 
- Existing tests should continue to pass.
> fix(logs): Fixing log messages

- src/Optimizely/ProjectConfigManager/HTTPProjectConfigManager.php
- tests/ProjectConfigManagerTests/HTTPProjectConfigManagerTest.php
This revises a couple of logs in HttpProjectConfigManager.
> refact: Revise ADF log more actionable

- src/Optimizely/Config/DatafileProjectConfig.php
- src/Optimizely/Config/ProjectConfigInterface.php
- src/Optimizely/OptimizelyConfig/OptimizelyConfig.php
- src/Optimizely/OptimizelyConfig/OptimizelyConfigService.php
- tests/ConfigTests/DatafileProjectConfigTest.php
- tests/OptimizelyConfigTests/OptimizelyConfigServiceTest.php
- tests/OptimizelyConfigTests/OptimizelyEntitiesTest.php
- toDatafile() method added in DatafileProjectConfig.
- getDatafile() method added in OptimizelyConfig
-  Unit tests added.
- FSC continues to pass.
https://travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/181695026
> feat: datafile accessor

- composer.json
All of the PHP versions that we support work well with Guzzle 6.2+. Our code is not compatible with Guzzle 5.3. Removed this from composer.json
All checks should pass.
> build: Update guzzle package version

- src/Optimizely/Enums/CommonAudienceEvaluationLogs.php
- src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
- src/Optimizely/Utils/SemVersionConditionEvaluator.php
- tests/UtilsTests/CustomAttributeConditionEvaluatorLoggingTest.php
- tests/UtilsTests/CustomAttributeConditionEvaluatorTest.php
- add greater than or equal and less than or equal for numbers
- add semantic version match types.
> feat: Semantic Versioning suppport in Audience Evaluation

- CHANGELOG.md
- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
Preparing for 3.5.0 release
- Unit tests pass.
> chore: Preparing for 3.5.0 release

- src/Optimizely/Event/Builder/EventBuilder.php
- src/Optimizely/Event/Builder/Params.php
- src/Optimizely/Optimizely.php
- tests/EventTests/EventBuilderTest.php
- tests/OptimizelyTest.php
- tests/TestData.php
1. Added "enabled" field to decision metadata structure
2. Setting "enabled" to true for activate() since we check for non null variation. 
1. Manuall tested thoroughly
2. Fixed existing unit tests
> feat: added "enabled" field to decision metadata structure

- src/Optimizely/Bucketer.php
- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/DecisionService/FeatureDecision.php
- src/Optimizely/Optimizely.php
- src/Optimizely/Utils/Validator.php
- tests/BucketerTest.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- tests/UtilsTests/ValidatorLoggingTest.php
- tests/UtilsTests/ValidatorTest.php
This PR refactors the way we collect logs for decideReasons. Previously, an array was being passed as reference to each method and each method appended it's log in the passed array. Now, each method returns it's logs along with it's response. 
- Modified Unit Tests.
- All existing checks should pass.
- "THING-1234" or "Fixes #123"
> refact: return decide reasons instead of appending to a reference parameter

- .travis.yml
- composer.json
- src/Optimizely/Bucketer.php
- src/Optimizely/Decide/OptimizelyDecideOption.php
- src/Optimizely/Decide/OptimizelyDecision.php
- src/Optimizely/Decide/OptimizelyDecisionMessage.php
- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/DecisionService/FeatureDecision.php
- src/Optimizely/Enums/DecisionNotificationTypes.php
- src/Optimizely/Optimizely.php
- src/Optimizely/OptimizelyUserContext.php
- src/Optimizely/Utils/Validator.php
- tests/BucketerTest.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- tests/OptimizelyUserContextTests.php
- tests/TestData.php
- tests/UtilsTests/ValidatorLoggingTest.php
- tests/UtilsTests/ValidatorTest.php
Added new APIs to support the decide feature. Introduced a new `OptimizelyUserContext ` class through `createUserContext` class api. This creates an optimizely instance with memoized user context and exposes the following APIs
1. `setAttribute`
2. `decide`
3. `decideAll`
4. `decideForKeys`
5. `trackEvent`
1. Manually tested thoroughly.
2. Added unit tests to cover new functionality. 
3. Tested with FSC manually.
> feat(Decide): Add Decide API

- src/Optimizely/Bucketer.php
- src/Optimizely/Config/DatafileProjectConfig.php
- src/Optimizely/Config/ProjectConfigInterface.php
- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/Event/Builder/EventBuilder.php
- src/Optimizely/Optimizely.php
- tests/ConfigTests/DatafileProjectConfigTest.php
- tests/EventTests/EventBuilderTest.php
- tests/OptimizelyTest.php
- tests/TestData.php
- Fixed an issue related to duplicate experimentKey.
- While trying to get variation from the variationKeyMap, it was unable to find because the latest experimentKey was overriding the previous one.
- Run with FSC
> feat: Duplicate experiment key issue with multi feature flag

- src/Optimizely/Config/DatafileProjectConfig.php
- src/Optimizely/Config/ProjectConfigInterface.php
- src/Optimizely/OptimizelyConfig/OptimizelyAttribute.php
- src/Optimizely/OptimizelyConfig/OptimizelyAudience.php
- src/Optimizely/OptimizelyConfig/OptimizelyConfig.php
- src/Optimizely/OptimizelyConfig/OptimizelyConfigService.php
- src/Optimizely/OptimizelyConfig/OptimizelyEvent.php
- src/Optimizely/OptimizelyConfig/OptimizelyFeature.php
- tests/OptimizelyConfigTests/OptimizelyConfigServiceTest.php
- tests/OptimizelyConfigTests/OptimizelyEntitiesTest.php
- tests/TestData.php
The following new public properties are added to OptimizelyConfig:
- sdkKey
- environmentKey
- attributes
- audiences
- events
- experimentRules and deliveryRules to OptimizelyFeature
- audiences to OptimizelyExperiment
All FSC tests OPTIMIZELY_CONFIG_V2 tests should pass.
https://app.travis-ci.com/github/optimizely/fullstack-sdk-compatibility-suite/builds/235923589
> feat(OptimizelyConfig): Add new fields to OptimizelyConfig

- src/Optimizely/Config/DatafileProjectConfig.php
- src/Optimizely/Config/ProjectConfigInterface.php
- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/Event/Builder/EventBuilder.php
- src/Optimizely/Optimizely.php
- src/Optimizely/OptimizelyUserContext.php
- src/Optimizely/Utils/Errors.php
- tests/ConfigTests/DatafileProjectConfigTest.php
- tests/DecisionServiceTests/DecisionServiceTest.php
- tests/OptimizelyTest.php
- tests/OptimizelyUserContextTest.php
- tests/TestData.php
Add a set of new APIs for forced-decisions to OptimizelyUserContext:
- setForcedDecision
- getForcedDecision
- removeForcedDecision
- removeAllForcedDecision
- unit tests for the new APIs
- FSC tests with new test cases
> feat(ForcedDecisions): add forced-decisions APIs to OptimizelyUserContext

- .travis.yml
- composer.json
- Monolog and guzzlehttp/guzzle version restriction removed.
All Existing unit and Integration tests pass
> chore: Removed Monolog version restriction

- src/Optimizely/OptimizelyUserContext.php
- tests/OptimizelyUserContextTest.php
- Remove config-ready check from forced-decision apis
- Unit and FSC tests
> fix(ForcedDecision): remove config-ready check from forced-decision apis

- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
- Searching forced decision variation from flags first if its not available then we search it in experiment variation map. This is because of forced decision setting variation of flag delivery rule and setting rule key of experiment rule 
All unit test and FSC tests should pass
> FIX: Forced variation not available in experiment

- src/Optimizely/DecisionService/DecisionService.php
- src/Optimizely/Optimizely.php
- src/Optimizely/OptimizelyUserContext.php
- Removed getFlagVariationByKey from optimizely and using it directly from project config.
- Moved findValidatedForcedDecision method to decision service to remove cyclic dependency.
All unit test and FSC tests should pass.
> refac: Moves findValidatedForcedDecision method to decision service

- src/Optimizely/OptimizelyUserContext.php
Since php 8.1 internal functions are using proper return types. This results in deprecation notices for some of the methods. To  suppress the notice for php8.1+ the proper return type or the new `ReturnTypeWillChange` attribute needs to be added to the method in question. If extending a class or implementing an interface (like `JsonSerializable `), the return type or attribute needs to be added as well. For more info check out https://stitcher.io/blog/new-in-php-81#interal-method-return-types-rfc
> Suppress jsonSerialize deprecation notice for php 8.1+

- src/Optimizely/ProjectConfigManager/HTTPProjectConfigManager.php
- By using `->getContents()` the actual string is returned instead of a Guzzle Stream object. The interface uses string everywhere.
> HTTPProjectConfigManager: datafile should be a string

- src/Optimizely/Config/DatafileProjectConfig.php
This PR is copied from PR-240 contributed by @adri, Since that PR is closed by the contributor so adding this PR.
- ProjectConfigInterface is the one used across SDK.
- All test must pass.
> fix(docs): Return type should be ProjectConfigInterface

- CHANGELOG.md
- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
> chore: prepare for release 3.9.1

- src/Optimizely/DecisionService/DecisionService.php
The following deprecation notice is popping up in conjunction with php 8.1 when calling `$optimizelyClient->setForcedVariation(...);` and the experiment is not active for the related environment.
> PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /path/to/project/vendor/optimizely/optimizely-sdk/src/Optimizely/DecisionService/DecisionService.php on line 557
In order to fix this it is necessary to cast `$experimentId` and `$variationId` to string when passing them to `strlen(...)` function in `Optimizely\DecisionService\DecisionService::setForcedVariation` method.
Detailed infos about the deprecation notice can be found here: https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation
> fix: avoid deprecation notices in php 8.1 when passing null to strlen

- README.md
- composer.json
- src/Optimizely/Config/DatafileProjectConfig.php
- src/Optimizely/Optimizely.php
- Update instances of Full Stack to Feature Experimentation
- Reformat README
- Add packagist badge
- Existing unit tests & FSC e2e tests should pass
-FSSDK-8963
> [FSSDK-8963] doc: Full Stack to Feature Experimentation Rename

- .github/workflows/php.yml
- src/Optimizely/OptimizelyUserContext.php
- src/Optimizely/UserProfile/UserProfileServiceInterface.php
- Check if testcases pass after fixing the hints as suggested in the PRs of the issue
- No changes here
- https://jira.sso.episerver.net/browse/FSSDK-8940
> [FSSDK-8940] Correct return type hints

- CHANGELOG.md
- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
- reverting minor release becasue it should be a major release. 
- we're still investigating if this release is a breaking change for some customers on older php bersions and what we want to do aboiut it. until then reverting.
https://jira.sso.episerver.net/browse/FSSDK-9415
> [FSSDK-9415] Revert minor release 3.10.0

- src/Optimizely/OptimizelyConfig/OptimizelyConfigService.php
- src/Optimizely/Utils/CustomAttributeConditionEvaluator.php
- tests/UtilsTests/CustomAttributeConditionEvaluatorLoggingTest.php
- tests/UtilsTests/CustomAttributeConditionEvaluatorTest.php
- Explicitly define class properties to get rid of deprecation warnings
- Internal pull request of third party PR 
[FSSDK-10015](https://jira.sso.episerver.net/browse/FSSDK-10015)
> [FSSDK-10015] Fix: Explicitly define class properties

- CHANGELOG.md
- src/Optimizely/Event/Builder/EventBuilder.php
- tests/EventTests/EventBuilderTest.php
- Update versions and changelog
- Existing unit and e2e tests are expected to succeed.
- [FSSDK-10015](https://jira.sso.episerver.net/browse/FSSDK-10015)
> [FSSDK-10015] chore: Prepare release 4.0.2
