composer.json
=> Allow monolog versions >= 1.21

src/Optimizely/Event/Builder/EventBuilder.php, src/Optimizely/Event/Builder/Params.php, src/Optimizely/ProjectConfig.php, tests/EventTests/EventBuilderTest.php, tests/ProjectConfigTest.php
=> Adding revision information to log events

src/Optimizely/Bucketer.php, src/Optimizely/DecisionService/DecisionService.php, src/Optimizely/Optimizely.php, tests/BucketerTest.php, tests/DecisionServiceTests/DecisionServiceTest.php, tests/OptimizelyTest.php
=> Introduce decision service

src/Optimizely/DecisionService/DecisionService.php, src/Optimizely/Optimizely.php, src/Optimizely/ProjectConfig.php, src/Optimizely/UserProfile/Decision.php, src/Optimizely/UserProfile/UserProfile.php, src/Optimizely/UserProfile/UserProfileServiceInterface.php, src/Optimizely/UserProfile/UserProfileUtils.php, tests/DecisionServiceTests/DecisionServiceTest.php, tests/ProjectConfigTest.php, tests/UserProfileTests/UserProfileTest.php, tests/UserProfileTests/UserProfileUtilsTest.php
=> Add user profile service

src/Optimizely/DecisionService/DecisionService.php, src/Optimizely/Event/Builder/EventBuilder.php
Also added comments to explain potential future changes, which I'll also create a Jira ticket for.
=> Changed the reserved keyword 

src/Optimizely/Event/Builder/EventBuilder.php, src/Optimizely/Event/Builder/Params.php, src/Optimizely/Utils/EventTagUtils.php, src/Optimizely/Utils/GeneratorUtils.php, tests/EventTests/EventBuilderTest.php, tests/UtilsTests/EventTagUtilsTest.php
✏️ New Payload
✏️ Numeric Event Support
✏️ Event Builder and Event Tags Unit Tests
=> New Event Builder Payload With Numeric Event Support

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> Bump to 1.4.0

src/Optimizely/Optimizely.php, tests/OptimizelyTest.php
=> Make NotificationListener public

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
Will go in after https://github.com/optimizely/php-sdk/pull/114
=> Preparing PHP SDK for release

src/Optimizely/DecisionService/DecisionService.php, src/Optimizely/Event/Builder/Params.php, src/Optimizely/Optimizely.php, src/Optimizely/ProjectConfig.php, tests/DecisionServiceTests/DecisionServiceTest.php, tests/OptimizelyTest.php, tests/UtilsTests/ValidatorTest.php
=> Minor cleanups

.github/pull_request_template.md, CONTRIBUTING.md
**Summary**
- Adds commit message guidelines in CONTRIBUTING.md
- Adds PR template for Github PRs
=> chore(contrib): Add PR template and commit message guidelines.

src/Optimizely/Notification/NotificationCenter.php
Addresses issue: https://github.com/optimizely/php-sdk/issues/122
=> Fix(phpdoc-notification-callback): Fixes phpdoc primitive type of notification-callback.

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> chore: Prepare 2.2.1 release.

CHANGELOG.md, src/Optimizely/Bucketer.php, src/Optimizely/Event/Builder/EventBuilder.php, src/Optimizely/Notification/NotificationCenter.php, tests/EventTests/EventBuilderTest.php
- Releases the fixes referenced in the commits for this PR
=> Merge 2.2.1 into release branch for release

.travis.yml
Coverage report is not being generated on coveralls. Fixing that.
Report gets generated
=> Fixing coveralls

src/Optimizely/DecisionService/DecisionService.php, src/Optimizely/DecisionService/FeatureDecision.php, src/Optimizely/Enums/DecisionInfoTypes.php, src/Optimizely/Notification/NotificationType.php, src/Optimizely/Optimizely.php, tests/DecisionServiceTests/DecisionServiceTest.php, tests/OptimizelyTest.php
Summary
-------
Implemented DecisionListener in following APIs:
- isFeatureEnabled
- getEnabledFeatures
Test plan
---------
Unit tests for DecisionListener
Issues
------
- OASIS-4234
=> feat(DecisionListener): Adds feature decision listener.

.travis.yml
This uses the script from travisci-tools repo to trigger compat suite. 
OASIS-4389
=> ci: Use travisci-tools script to trigger tests 

src/Optimizely/DecisionService/DecisionService.php
- Picked whitelisted variation changes from 3.0 to 2.2.x.
=> fix(whitelisting): Whitelisted variation should continue when no valid variation is found.

.travis.yml
https://github.com/travis-ci/travis-ci/issues/9881
=> ci(travis): trusty needed for php55 support

CHANGELOG.md
- Updated the 3.2.0 changelog for config update notification
=> chore: Updated the 3.2.0 changelog for config update notification

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> chore: prepare for release 3.3.1

src/Optimizely/Entity/FeatureVariable.php, src/Optimizely/Optimizely.php, tests/OptimizelyTest.php
This PR changes the method name as in the title. 
All checks continue to pass.
=> refact: changed getFeatureVariableJson to getFeatureVariableJSON

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
`CHANGELOG` and other updates for releasing version 3.6.0
=> chore: Preparing for release 3.6.0

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> chore: prepare for release 3.7.0

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> chore: prepare for release 3.7.1

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> chore: prepare for release 3.8.0

src/Optimizely/Event/Builder/EventBuilder.php
- Impression Param implementation refactoring
- Should pass all unit tests and FSC tests.
=> refact: Impression event correction

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
=> chore: prepare for release 3.9.0

src/Optimizely/ProjectConfigManager/HTTPProjectConfigManager.php
#243 header was not updated, updating in this PR.
Should pass all scenarios and unit tests.
=> fix: header updated.

src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
- incrementing the patch version number for documentation
Existing CI and FSC tests should pass
- FSSDK-8963
=> [FSSDK-8963] chore: Version Increment

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
- Prepare for release 3.9.4
- https://jira.sso.episerver.net/browse/FSSDK-8940
=> [FSSDK-8940] Prepare for release 3.9.4

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
- sdk minor version bump
- release notes
- changelog update
- [FSSDK-9415 Release php sdk minor version 3.10.0](https://jira.sso.episerver.net/browse/FSSDK-9415)
=> [FSSDK-9415] PHP v8.x Release - SDK minor release 3.10.0

README.md, composer.json, composer.lock, src/Optimizely/Decide/OptimizelyDecision.php, src/Optimizely/OptimizelyConfig/OptimizelyAttribute.php, src/Optimizely/OptimizelyConfig/OptimizelyAudience.php, src/Optimizely/OptimizelyConfig/OptimizelyConfig.php, src/Optimizely/OptimizelyConfig/OptimizelyEvent.php, src/Optimizely/OptimizelyConfig/OptimizelyExperiment.php, src/Optimizely/OptimizelyConfig/OptimizelyFeature.php, src/Optimizely/OptimizelyConfig/OptimizelyVariable.php, src/Optimizely/OptimizelyConfig/OptimizelyVariation.php
- Update README to fix code examples
- Add sort-packages 
- Add `ReturnTypeWillChange` decorators
- All existing unit tests and end-to-end FSC tests are expected to pass
- FSSDK-9630
=> [FSSDK-9630] Fix: Code examples

CHANGELOG.md, src/Optimizely/Event/Builder/EventBuilder.php, tests/EventTests/EventBuilderTest.php
- Update versions and changelog
- Existing unit and e2e tests are expected to succeed.
- FSSDK-9784
=> [FSSDK-9784] chore: Prepare release 4.0.1
